### ISSUE TITLE
pr-review-gate: mirror job cannot load its resolver script, so `AI review required` is red on every PR

### ISSUE THREAD

**Issue by ohthehugemanatee** [ohthehugemanatee/homenet-documentation#205]
## Problem

`AI review required` currently fails on **every** PR in this repo. #204 had to be merged around it.

The AI review itself passes — the gate is reporting a *missing* check, not a failed review.

The `workflow_run` half of the `gate` job in `.github/workflows/pr-review-gate.yaml` is supposed to mirror a finished review's result onto the reviewed SHA:

```js
const { resolveMirrorTarget } = require('${{ github.workspace }}/.github/scripts/resolve-review-head-sha.js');
```

It crashes every time ([example run](https://github.com/ohthehugemanatee/homenet-documentation/actions/runs/31326151622)):

```
Error: Cannot find module '/home/runner/work/homenet-documentation/homenet-documentation/.github/scripts/resolve-review-head-sha.js'
  code: 'MODULE_NOT_FOUND'
```

Because it dies before `checks.create`, the passing check is never posted. The `pull_request` half of the gate then correctly reports `No passing AI Infrastructure Review found for <sha>` and exits 1.

## Two bugs, not one

1. **No checkout.** `grep -c "actions/checkout" .github/workflows/pr-review-gate.yaml` → `0`. `github.workspace` is empty, so the `require` resolves to a path that does not exist.

2. **`contents` is `none`.** The workflow's `permissions:` block lists only:
   ```yaml
   permissions:
     pull-requests: write
     actions: read
     checks: write
   ```
   An explicit `permissions:` block sets every unlisted scope to `none`, so `contents` is `none`. **Adding a checkout step alone would trade `MODULE_NOT_FOUND` for a 403** — the fix needs both.

Both were introduced together in 096fec2 (#199), which added the `require()` without either. The `workflow_run` gate run has concluded `failure` on unrelated commits on 2026-07-30 and 2026-08-08, so this has been broken since #199 landed.

## Spec

**Intent:** a completed AI review posts a passing `AI review required` check onto the SHA it reviewed, so PRs stop needing a manual override to merge.

**Resources touched:** `.github/workflows/pr-review-gate.yaml`, `.github/workflows/lint.yaml`. No cluster resources, no namespace, no host.

### Expected end state

- `permissions:` gains `contents: read`.
- The `gate` job checks out before the mirror step, guarded to `github.event_name == 'workflow_run'` and pinned to the default branch:
  ```yaml
  - name: Check out gate scripts
    if: github.event_name == 'workflow_run'
    uses: actions/checkout@v4
    with:
      # Pin to the default branch: this job holds checks:write + pull-requests:write,
      # so it must never check out the PR head it is about to rule on.
      ref: ${{ github.event.repository.default_branch }}
      persist-credentials: false
  ```
  Pinning `ref` explicitly is the point — it makes the trust boundary independent of whatever `workflow_run`'s default checkout ref happens to be.
- CI asserts the wiring invariant so this cannot silently regress.

Do **not** inline the resolver to dodge the checkout. `.github/CLAUDE.md` documents the extraction as deliberate ("so a superseded/cancelled review run can't post its result onto a newer, unreviewed commit"), and inlining would drop it out of `node --test` coverage.

### Test-first

A unit test of the resolver cannot catch this — the resolver is fine, and its four tests in `.github/scripts/tests/resolve-review-head-sha.test.js` already pass. The regression test has to assert the *wiring*.

There is no `package.json`, so the `github-scripts` job (`lint.yaml:114-120`) runs `node --test` with builtins only — no `js-yaml` for parsing workflow YAML in JS. Use PyYAML instead (preinstalled on the ubuntu runner), matching the `python3 - <<'PY'` + `yaml.safe_load` pattern already used in `test-cluster.yaml`.

Add a second step to the existing `github-scripts` job, after `Run unit tests`:

- Walk every `.github/workflows/*.yaml`, every job, every step in order.
- Track whether an `actions/checkout` step has been seen in that job yet.
- If a step's `with.script` references `github.workspace` and no checkout preceded it in the same job, print `BAD <file>:<job>: <step name>` and exit 1.

Red today against `pr-review-gate.yaml`, green after the fix, and it generalizes to any future workflow with the same mistake.

### Acceptance criterion

A completed AI Infrastructure Review run results in a passing `AI review required` check on the reviewed SHA, and the AI Review Gate `workflow_run` run completes `success` rather than `MODULE_NOT_FOUND`.

## Bootstrapping problem — read before merging

The fix PR is itself gated by the broken gate. `workflow_run` jobs always run the **default branch** copy of the workflow, so the repaired version does not take effect until it is on `master`. The gate stays red on the fix PR itself.

Break the cycle once, either way:

- Actions → **AI Review Gate** → Run workflow, with `pr_number` and the exact `sha` — the `workflow_dispatch` path `pr-review-gate.yaml` already documents for exactly this case. It posts the passing check plus an audit comment.
- Or an admin merge, as #204 got.

After it lands on `master`, every subsequent PR mirrors normally with no override.

## Verification

Before commit:

```sh
node --test ".github/scripts/tests/*.test.js"   # 4 existing resolver tests, still green
yamllint .
# the new assertion, run standalone — confirm red before the fix, green after
```

`shellcheck` / `ansible-lint` are no-ops — no shell or Ansible files in the diff.

After merge (the part no local test can prove):

- Open any PR, or `workflow_dispatch` **AI Infrastructure Review** against an open one.
- Watch the AI Review Gate `workflow_run` run complete `success`.
- Confirm a passing `AI review required` check lands on that PR's head SHA and `mergeable_state` leaves `unstable`.

**Rollback:** revert. The gate returns to today's behavior — red on every PR, with the documented `workflow_dispatch` override still available.

## Docs

`.github/CLAUDE.md`'s workflow-inventory line describes the gate as delegating SHA/PR selection to `scripts/resolve-review-head-sha.js`, which stays true after this fix. Checked — no doc change needed.

## Out of scope

The gate's `pull_request` trigger types are `[synchronize, reopened, ready_for_review]` with no `opened`, so a PR that is opened and never pushed to gets no gate check from that path until the mirror posts one. Separate latent issue, its own Issue if it's worth fixing.

~20 LOC across two files.
